In [2]:
import numpy as np

def function(d, D):
    delta = arctan(d / (2*D))
    return(delta)

d = float(input("d="))
D = float(input("D="))
print(np.degrees(function(d, D)))

d= 6
D= 7


23.198590513648185


In [10]:
from numpy import pi

def cylinder(r, h):
    A = 2 * pi * r**2 + 2 * pi * r * h
    V = pi * r**2 * h
    return A, V, A/V

print(cylinder(5, 7))

(376.99111843077515, 549.7787143782139, 0.6857142857142856)


In [118]:
import numpy as np

x = [1, 10**2, 2*10, 5.1*20, -4, 4.45*22]
arrx = np.array(x)
print(arr)
y = np.random.uniform(1, 2.5, size = 19)
y2 = np.append(y, 2.5)

print(y2)

p = np.arange(1, 2.5, 0.1)

print(p)

np.where(arrx > 5)
yflip = np.flip(y)
print(yflip[0: 10])


[  1.  100.   20.  102.   -4.   97.9]
[1.6882337  1.94493032 1.44638518 1.28197692 1.29877267 1.8398478
 1.38748888 2.34124823 1.62843792 1.21383746 2.26306256 1.68392215
 1.53321974 1.18842173 1.50605478 1.75453046 1.56472477 1.26798248
 1.85478117 2.5       ]
[1.  1.1 1.2 1.3 1.4 1.5 1.6 1.7 1.8 1.9 2.  2.1 2.2 2.3 2.4]
[1.85478117 1.26798248 1.56472477 1.75453046 1.50605478 1.18842173
 1.53321974 1.68392215 2.26306256 1.21383746]


In [119]:
import numpy as np
x = np.random.normal(0, 5, 10000)
where = np.where(x > 5)
print(where)

yflip = np.flip(x)
print(yflip[0: 10])

(array([   3,    7,   23, ..., 9994, 9997, 9998], shape=(1558,)),)
[ 1.25832564  8.31778345  6.14693864 -5.91356642 -6.21894994  7.11012592
 12.70483409 -8.27604934  6.44175998  2.46200609]


10000

In [111]:
import numpy as np
rng.integers(low=0, high=1, size=10)
np.random.rand(10) + 1j * np.random.rand(10)

array([6.86301045e-01+0.05456724j, 3.72537760e-01+0.19652506j,
       7.59453132e-01+0.26017219j, 2.32601107e-01+0.19312529j,
       1.27508580e-04+0.6669825j , 6.95033862e-01+0.34468529j,
       1.03736236e-01+0.21974084j, 2.19559109e-01+0.38654194j,
       2.16024610e-03+0.65483511j, 8.41132772e-01+0.75418324j])

In [144]:
import numpy as np

def stdev(p, N):
    y = p
    mu = 0
    sigma = 0
    for i in range(0,N):
        mu +=  y[i]
    mu = mu/N
    for i in range(0,N): 
        sigma += 1/N * (y[i] - mu)**2
    return sigma**0.5

array = np.random.normal(0, 5, 1000)
print(stdev(array, len(array)))

print(np.std(array))

4.918426378428275
4.918426378428275


In [152]:
list = [18.49, 2094.75,
35.48, 2320.87,
35.48, 1224.9,
11.34, 872.13,
7.12,  432.2,
9.82,  751,
23.66, 1410,
44,    2700,
66.7,  5292,
52.4, 2550,
55,    5253,
25.6,  2419,
26.19, 2158]

print(list)

[18.49, 2094.75, 35.48, 2320.87, 35.48, 1224.9, 11.34, 872.13, 7.12, 432.2, 9.82, 751, 23.66, 1410, 44, 2700, 66.7, 5292, 52.4, 2550, 55, 5253, 25.6, 2419, 26.19, 2158]
